[2025-06-05T14:41:34.554-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netflix_retention_dag.load_csv_to_postgres manual__2025-06-05T18:41:30.817381+00:00 [queued]>
[2025-06-05T14:41:34.557-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netflix_retention_dag.load_csv_to_postgres manual__2025-06-05T18:41:30.817381+00:00 [queued]>
[2025-06-05T14:41:34.557-0400] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-05T14:41:34.561-0400] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_csv_to_postgres> on 2025-06-05 18:41:30.817381+00:00
[2025-06-05T14:41:34.563-0400] {standard_task_runner.py:60} INFO - Started process 61471 to run task
[2025-06-05T14:41:34.568-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'netflix_retention_dag', 'load_csv_to_postgres', 'manual__2025-06-05T18:41:30.817381+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/netflix_retention_dag.py', '--cfg-path', '/var/folders/h9/p5fdhb7n7s964d6sg7dxh0rw0000gn/T/tmpgfi3inwy']
[2025-06-05T14:41:34.570-0400] {standard_task_runner.py:88} INFO - Job 11: Subtask load_csv_to_postgres
[2025-06-05T14:41:34.587-0400] {task_command.py:423} INFO - Running <TaskInstance: netflix_retention_dag.load_csv_to_postgres manual__2025-06-05T18:41:30.817381+00:00 [running]> on host mac.lan1
[2025-06-05T14:41:34.607-0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='netflix_retention_dag' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T18:41:30.817381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T18:41:30.817381+00:00'
[2025-06-05T14:41:34.607-0400] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/h9/p5fdhb7n7s964d6sg7dxh0rw0000gn/T
[2025-06-05T14:41:34.608-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "PWD=$(pwd)"; ls -la; cd /Users/vionasanda/Projects/netflix-retention-project && python etl/load_csv_to_postgres.py']
[2025-06-05T14:41:34.611-0400] {subprocess.py:86} INFO - Output:
[2025-06-05T14:41:34.616-0400] {subprocess.py:93} INFO - PWD=/private/var/folders/h9/p5fdhb7n7s964d6sg7dxh0rw0000gn/T/airflowtmp6vv8x5pm
[2025-06-05T14:41:34.618-0400] {subprocess.py:93} INFO - total 0
[2025-06-05T14:41:34.619-0400] {subprocess.py:93} INFO - drwx------@   2 vionasanda  staff    64 Jun  5 14:41 .
[2025-06-05T14:41:34.619-0400] {subprocess.py:93} INFO - drwx------@ 253 vionasanda  staff  8096 Jun  5 14:41 ..
[2025-06-05T14:41:34.899-0400] {subprocess.py:93} INFO - /Users/vionasanda/Projects/netflix-retention-project/etl/load_csv_to_postgres.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-05T14:41:34.900-0400] {subprocess.py:93} INFO -   users.to_sql("users", engine, index=False, if_exists="append")
[2025-06-05T14:41:34.900-0400] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-05T14:41:34.900-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/etl/load_csv_to_postgres.py", line 41, in <module>
[2025-06-05T14:41:34.900-0400] {subprocess.py:93} INFO -     load_csv_to_postgres()
[2025-06-05T14:41:34.901-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/etl/load_csv_to_postgres.py", line 17, in load_csv_to_postgres
[2025-06-05T14:41:34.901-0400] {subprocess.py:93} INFO -     users.to_sql("users", engine, index=False, if_exists="append")
[2025-06-05T14:41:34.901-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
[2025-06-05T14:41:34.901-0400] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-05T14:41:34.901-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3087, in to_sql
[2025-06-05T14:41:34.901-0400] {subprocess.py:93} INFO -     return sql.to_sql(
[2025-06-05T14:41:34.902-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 842, in to_sql
[2025-06-05T14:41:34.902-0400] {subprocess.py:93} INFO -     return pandas_sql.to_sql(
[2025-06-05T14:41:34.902-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2850, in to_sql
[2025-06-05T14:41:34.902-0400] {subprocess.py:93} INFO -     table.create()
[2025-06-05T14:41:34.902-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 984, in create
[2025-06-05T14:41:34.903-0400] {subprocess.py:93} INFO -     if self.exists():
[2025-06-05T14:41:34.903-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 970, in exists
[2025-06-05T14:41:34.903-0400] {subprocess.py:93} INFO -     return self.pd_sql.has_table(self.name, self.schema)
[2025-06-05T14:41:34.903-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2865, in has_table
[2025-06-05T14:41:34.903-0400] {subprocess.py:93} INFO -     return len(self.execute(query, [name]).fetchall()) > 0
[2025-06-05T14:41:34.903-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2672, in execute
[2025-06-05T14:41:34.904-0400] {subprocess.py:93} INFO -     cur = self.con.cursor()
[2025-06-05T14:41:34.904-0400] {subprocess.py:93} INFO - AttributeError: 'Engine' object has no attribute 'cursor'
[2025-06-05T14:41:34.927-0400] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-05T14:41:34.930-0400] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-05T14:41:34.938-0400] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=netflix_retention_dag, task_id=load_csv_to_postgres, execution_date=20250605T184130, start_date=20250605T184134, end_date=20250605T184134
[2025-06-05T14:41:34.942-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task load_csv_to_postgres (Bash command failed. The command returned a non-zero exit code 1.; 61471)
[2025-06-05T14:41:34.952-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-05T14:41:34.959-0400] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
